CREATE TABLE ecommerce5;
USE ecommerce5;
CREATE TABLE IF NOT EXISTS todos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);


CREATE TABLE `user` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    image VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    dateOfBirthday DATE,
    gender VARCHAR(255),
    address VARCHAR(255) DEFAULT '',
    role INT DEFAULT 1,
    active BOOLEAN DEFAULT FALSE
);

